[package]
name = "osti"
description = "A terminal, keyboard-driven, modal tool for composing music"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
